FROM python:3.12-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml .
RUN uv sync --no-dev

# Download SpaCy Russian model
RUN uv run python -m spacy download ru_core_news_sm

COPY worker/ ./worker/

CMD ["uv", "run", "python", "-m", "worker.__main__"]
